# Generated by Django 5.2.7 on 2025-11-02 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_contact_uploaded_date_contact_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created_date']},
        ),
    ]
