# Generated by Django 5.2.7 on 2025-11-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField()),
                ('created_date', models.DateTimeField()),
                ('uploaded_date', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('counted_view', models.IntegerField()),
            ],
        ),
    ]
